### ISSUE TITLE
Terminal does not wrap input line & keyboard paste not working

### ISSUE THREAD

**Issue by Morabaraba** [exsilium/cloud9#21]
Not sure if this is a issue with the terminal or my idea of how the terminal must work.

But when you reach the end of the line it does not wrap the input to the next line. But rather restart input on the same line, overwriting any text in its way.

A side node, I'm on a mac and cmd+v works in the editor but not on the terminal. But double click paste, so I'm using that atm but moving my hand from the keyboard is a erk!

Thanks for maintaining this and making sure it runs nicely.

**Comment by exsilium** [comment]
Hi! Glad to hear you are still enjoying the GPL version of Cloud9 ;)

Your understanding of how terminal **should** work is spot on. The current implementation of term.js doesn't handle overflowing - a clear bug.

As for the pasting via keyboard - the terminal canvas is non-contentEditable surface, thus the paste event is not getting through. The copy/paste functionality is mouse-driven. Selecting some text copies it to the internal apf clipboard and right-clicking on the terminal surface pastes the internal apf clipboard.

The same logic could be extended to accept <kbd>Cmd</kbd>+<kbd>v</kbd> or <kbd>Ctrl</kbd>+<kbd>v</kbd>

This would help in copying content from and between the Cloud9 editor, but not from external clipboard.

Longer term fix would be to rework the terminal plugin to use xterm.js instead of the legacy term.js.

**Comment by exsilium** [comment]
@Morabaraba - I believe I found a workaround solution to make the keyboard paste work by giving temporary focus to the shadow textarea. It works for me in Mac using Safari. Let me know if it works for you as well. Cheers!

**Comment by Morabaraba** [comment]
Tested on Win 10 chrome (~~and edge~~ nope #22), thanks. Will test on a mac soon.

First tried a npm update on the project to get your ctrl+v change. Realised I need to git clone https://github.com/exsilium/term.js.git instead.
It to crude?

dump of `stdout` here: https://gist.github.com/Morabaraba/29c0109f614033d8433a0c4566aef758

> Longer term fix would be to rework the terminal plugin to use xterm.js instead of the legacy term.js.

Thanks for the info, any idea what the scope of this fix would be?

> Hi! Glad to hear you are still enjoying the GPL version of Cloud9 ;)

I like my addications to be free :)

**Comment by exsilium** [comment]
Indeed, the term.js is consumed in an unversioned state directly from the github repo you linked. Easiest way is to `rm -rf ./node_modules/term.js` and rerun `npm install` - that should do it. It always fetches the master tarball. Unless, for some reason, it's cached in npm, in which case `npm cache clean` would help.

> Thanks for the info, any idea what the scope of this fix would be?

It's hard to say. I've taken a peek now and then @ xterm.js project - they have refactored the code to the extent that it no longer resembles term.js - thus it's hard to tell how much work it would take. But it would benefit to move to the active branch to get all the fixes and features for free 👍

**Comment by exsilium** [comment]
Xterm paste via keyboard seems not to work on windows: sourcelair/xterm.js#491 & sourcelair/xterm.js#487
